[graph]
targets = [
    "aarch64-apple-darwin",
    "x86_64-apple-darwin",
    "x86_64-pc-windows-msvc",
    "i686-pc-windows-msvc",
]
all-features = true

[advisories]
unmaintained = "workspace"
ignore = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"

[licenses]
confidence-threshold = 0.93
allow = [
    "Apache-2.0",
    "MIT",
    "ISC",
]
exceptions = [
    { allow = ["Unicode-3.0"], crate = "unicode-ident" },
]
