/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * A suggestion for a misspelled word.
 *
 * @typedef {Object} Suggestion
 * @property {number} start The start index of the string
 * @property {number} end The end index of the string
 * @property {string} word The misspelled word
 * @property {string[]} suggestions The list of suggested words
 */
export interface Suggestion {
  /** The start index of the misspelled word in the original text. */
  start: number
  /** The end index of the misspelled word in the original text. */
  end: number
  /** The misspelled word. */
  word: string
  /** A list of suggested corrections for the misspelled word. */
  suggestions: Array<string>
}
/**
 * The main Spell checker class.
 *
 * This automatically determine the appropriate spell checker implementation based on the platform.
 *
 * As a sidenote, all API returned can throw an error, especially on Windows.
 *
 * @class SpellChecker
 */
export declare class SpellChecker {
  /** Create a new instance of the spell checker. */
  constructor()
  /**
   * Get the current language of the spell checker.
   *
   * @returns {string | null}
   */
  language(): string | null
  /**
   * Set the language for the spell checker.
   *
   * @param {string} language The preferred spell checker language.
   * @returns {void}
   */
  setLanguage(language: string): void
  /**
   * Get the list of available languages for the spell checker.
   *
   * @returns {string[]} A list of available languages.
   */
  availableLanguages(): Array<string>
  /**
   * Check if a word is spelled correctly.
   *
   * @param {string} word The word to check
   * @returns {boolean} Is the word spelled correctly or not.
   */
  checkWord(word: string): boolean
  /**
   * Check if a word is spelled correctly.
   *
   * This will also return a list of suggestions if the word is misspelled.
   *
   * @param {string} sentences The sentences to check
   * @returns {Suggestion[]} The list of suggested spellings.
   */
  checkAndSuggest(sentences: string): Array<Suggestion>
  /**
   * Add a single word to the spell checker.
   *
   * @param {string} word The word to add
   * @returns {void}
   */
  addWord(word: string): void
  /**
   * Add words to the spell checker.
   *
   * @param {string[]} words The words to add
   * @returns {void}
   */
  addWords(words: Array<string>): void
  /**
   * Remove a single word from the spell checker.
   *
   * ## Note
   * On Windows, this will always just silently fails.
   *
   * @param {string} word The word to remove
   * @returns {void}
   */
  removeWord(word: string): void
  /**
   * Remove words from the spell checker.
   *
   * ## Note
   * On Windows, this will always just silently fails.
   *
   * @param {string[]} words The words to remove
   * @returns {void}
   */
  removeWords(words: Array<string>): void
}
