/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** A suggestion for a misspelled word. */
export interface Suggestion {
  /** The start index of the misspelled word in the original text. */
  start: number
  /** The end index of the misspelled word in the original text. */
  end: number
  /** The misspelled word. */
  word: string
  /** A list of suggested corrections for the misspelled word. */
  suggestions: Array<string>
}
/**
 * The main Spell checker class.
 *
 * This automatically determine the appropriate spell checker implementation based on the platform.
 */
export declare class SpellChecker {
  /** Create a new instance of the spell checker. */
  constructor()
  /** Get the current language of the spell checker. */
  language(): string | null
  /** Set the language for the spell checker. */
  setLanguage(language: string): void
  /**
   * Get the list of available languages for the spell checker.
   *
   * # Returns
   * A list of available languages.
   */
  availableLanguages(): Array<string>
  /**
   * Check if a word is spelled correctly.
   *
   * # Arguments
   * * `word` - The word to check.
   */
  checkWord(word: string): boolean
  /**
   * Check if a word is spelled correctly.
   *
   * This will also return a list of suggestions if the word is misspelled.
   *
   * # Arguments
   * * `sentences` - The sentence to check.
   */
  checkAndSuggest(sentences: string): Array<Suggestion>
  /**
   * Add a single word to the spell checker.
   *
   * # Arguments
   * * `word` - The word to add.
   */
  addWord(word: string): void
  /**
   * Add a words to the spell checker.
   *
   * # Arguments
   * * `words` - The words to add.
   */
  addWords(words: Array<string>): void
  /**
   * Remove a single word from the spell checker.
   *
   * # Arguments
   * * `word` - The word to remove.
   *
   * # Note
   * On Windows, this will always just silently fails.
   */
  removeWord(word: string): void
  /**
   * Remove words from the spell checker.
   *
   * # Arguments
   * * `words` - The words to remove.
   *
   * # Note
   * On Windows, this will always just silently fails.
   */
  removeWords(words: Array<string>): void
}
